### ISSUE TITLE
404 when connecting to localhost (docker)

### ISSUE THREAD

**Issue by MikeS-nth** [pgonzaleznetwork/sfdc-happy-soup#156]
Hello,

I am trying to run Happy Soup locally using Docker via [these instructions](https://www.youtube.com/watch?v=WQhz91JSl3o).

`npm run dc-build` seems to run successfully; however, when I try to connect via http://localhost:3000, I get the following error:

`{
  "error": true,
  "statusCode": 404,
  "message": "Not Found",
  "stack": "NotFoundError: Not Found\n    at /app/backend/server/app.js:45:8\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)\n    at /app/node_modules/express/lib/router/index.js:284:7\n    at Function.process_params (/app/node_modules/express/lib/router/index.js:335:12)\n    at next (/app/node_modules/express/lib/router/index.js:275:10)\n    at /app/backend/server/app.js:25:5\n    at Layer.handle [as handle_request] (/app/node_modules/express/lib/router/layer.js:95:5)\n    at trim_prefix (/app/node_modules/express/lib/router/index.js:317:13)\n    at /app/node_modules/express/lib/router/index.js:284:7"
}`

Here is my `docker-compose.yml` (keys redacted)

```
version: '3'

services:
  redis:
    image: 'redis'
  webapp:
    build:
      context: .
      dockerfile: ./docker/web/Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OAUTH_CLIENT_ID=#KEY
      - OAUTH_CLIENT_SECRET=#KEY
      - SFDC_API_VERSION=49.0
      - SESSION_SECRET=whatever
      - PORT=3000
      - CORS_DOMAINS=http://localhost:3000,https://sfdc-happy-soup.herokuapp.com,https://happysoup.io
      - ENFORCE_SSL=false
  worker:
    build:
      context: .
      dockerfile: ./docker/worker/Dockerfile
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - OAUTH_CLIENT_ID=#KEY
      - OAUTH_CLIENT_SECRET=#KEY
      - SFDC_API_VERSION=49.0
      - SESSION_SECRET=whatever
      - PORT=3000
      - CORS_DOMAINS=http://localhost:3000,https://sfdc-happy-soup.herokuapp.com,https://happysoup.io
      - ENFORCE_SSL=false
```

Any assistance is greatly appreciated!!
